<h1 class="page-header text-info">Distributors</h1>

  <div class="row">
      <?php foreach ($this->messages as $message) : ?>
		<li class="label label-danger"><?php echo $this->escape($message); ?></li>
<?php endforeach; ?>
                
      <a href="<?php echo $this->baseUrl();?>/distributors/add" class="btn btn-primary pull-right">Add Distributors</a><br /><br />
          <div class="table-responsive">
            <table class="table table-striped table-bordered">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Name</th>
                  <th>Email</th>
                  <th>Contact no</th>
                  <th>Address</th>
                  <th>Status</th>
                  <th>Action</th>
                </tr>
              </thead>
              <tbody>
    <?php foreach ( $this->distributors as $i => $distributors ): ?>
                <tr>
                  <td><?php echo $i+1; ?></td>
                  <td><?php echo $distributors['initial_name']; ?> <?php echo $distributors['name']; ?></td>
                  <td><?php echo $distributors['email']; ?></td>
                  <td><?php echo $distributors['contact_no']; ?></td>
                  <td><?php echo $distributors['address']; ?></td>
                  <td>
                      <?php if( $distributors['status'] == 'Active') : ?>
                      <span  class="label label-success"><?php echo $distributors['status']; ?></span>
                      <?php else : ?>
                      <span  class="label label-danger"><?php echo $distributors['status']; ?></span>
                      <?php endif;?>
                  </td>
                  
                  <td>
                  <a href="<?php echo $this->baseUrl(); ?>/demands/add/?id=<?php echo $distributors['id']; ?>" class="btn btn-sm btn-success">Add Demand</a>
                  <a href="<?php echo $this->baseUrl(); ?>/distributors/index/delete/?id=<?php echo $distributors['id']; ?>" class="btn btn-sm btn-danger">Delete</a>
                  <a href="<?php echo $this->baseUrl(); ?>/distributors/edit/?id=<?php echo $distributors['id']; ?>" class="btn btn-sm btn-info">Edit</a>
                  
                  </td>
                </tr>
    <?php endforeach; ?>
              </tbody>
              <tfoot>
                <tr>
                    <td colspan="12" align="middle"><?php echo $this->paginationControl($this->distributors,
                                    'Sliding',
                                    'my_pagination_control.phtml'); ?></td>
                </tr>
              </tfoot>
            </table>
            
          </div>
        </div>