<h1 class="page-header">Edit Product</h1>
<div class="breadcrumb"><a href="<?php echo $this->baseUrl();?>/dashboard" class="small">Dashboard</a> / <a href="<?php echo $this->baseUrl();?>/products" class="small">Products</a> / <span class="small text-muted">Edit</span></div>
<div class="row">
<?php foreach ( $this->messages as $msg ) : ?>
     <?php echo $msg; ?>
<?php endforeach;?>
    
    <form role="form" method="post" class="well">
        <div class="form-group">
    <label for="name">Name</label>
    <input type="text" class="form-control" id="name" name="name" placeholder="Name" value="<?php echo $this->products['name'];?>">
  </div>
   
   <div class="form-group ">
    <label for="mrp">MRP</label>
    <div class="input-group">
    <span class="input-group-addon">Rs - /</span>
    <input type="text" class="form-control" id="mrp" name="mrp" placeholder="Enter price" value="<?php echo $this->products['mrp'];?>">
    <span class="input-group-addon">Per / Ltr</span>
    </div>
  </div>
  
  <div class="form-group ">
    <label for="fact_price">Fact price</label>
    <div class="input-group">
    <span class="input-group-addon">Rs - /</span>
    <input type="text" class="form-control" id="fact_price" name="fact_price" placeholder="Enter price" value="<?php echo $this->products['fact_price'];?>">
    <span class="input-group-addon">Per / Ltr</span>
    </div>
  </div>
   
  <div class="form-group ">
    <label for="price">Price</label>
    <div class="input-group">
    <span class="input-group-addon">Rs - /</span>
    <input type="text" class="form-control" id="price" name="price" placeholder="Enter price" value="<?php echo $this->products['price'];?>">
    <span class="input-group-addon">Per / Caret</span>
    </div>
  </div>
  
  <div class="form-group ">
    <label for="discount">Discount</label>
    <div class="input-group">
    <span class="input-group-addon">Rs - /</span>
    <input type="text" class="form-control" id="discount" name="discount" placeholder="Enter price" value="<?php echo $this->products['discount'];?>"> 
    <span class="input-group-addon">Per / Caret</span>
    </div>
  </div>
  
  <div class="form-group">
    <label for="qty">Quantity</label>
    <div class="input-group">
    <input type="text" class="form-control" id="qty" name="qty" placeholder="Quantity" value="<?php echo $this->products['qty'];?>">
    <span class="input-group-addon">Caret</span>
    </div>
  </div>
  <div class="checkbox">
    <label>
        <input type="checkbox" name="status" value="Active" <?php echo $this->products['status'] == 'Active'? 'Checked':''; ?>> Active
    </label>
  </div>
  <input type="hidden" name="id" value="<?php echo $this->products['id'];?>" />
  <button type="submit" class="btn btn-default">Submit</button>
</form>
</div>