<h1 class="page-header">Users</h1>

<div class="row">
<?php foreach ( $this->messages as $msg ) : ?>
     <?php echo $msg; ?>
<?php endforeach;?>
    
    <form role="form" method="post">
        <div class="form-group">
    <label for="name">Name</label>
    <input type="text" class="form-control" id="name" name="name" placeholder="Name">
  </div>
   
     <div class="form-group">
    <label for="role">Role</label>
    <select name="type" class="form-control">
        <option value="">select</option>
        <?php foreach ( $this->users_role as $ur ) : ?>
        <option value="<?php echo $ur['id']; ?>"><?php echo $ur['name']; ?></option>
        <?php endforeach;?>
    </select>
  </div>
   
  <div class="form-group">
    <label for="email">Email address</label>
    <input type="email" class="form-control" id="email" name="email" placeholder="Enter email">
  </div>
  <div class="form-group">
    <label for="password">Password</label>
    <input type="password" class="form-control" id="password" name="password" placeholder="Password">
  </div>
  <div class="checkbox">
    <label>
        <input type="checkbox" name="status" value="Active"> Active
    </label>
  </div>
  <button type="submit" class="btn btn-default">Submit</button>
</form>
</div>