<h1 class="page-header text-info">Products</h1>

<div class="breadcrumb"><a href="<?php echo $this->baseUrl();?>/dashboard" class="small">Dashboard</a> / <span class="small text-muted">Products</span></div>
  <div class="row">
      <?php foreach ($this->messages as $message) : ?>
		<li class="label label-danger"><?php echo $this->escape($message); ?></li>
<?php endforeach; ?>
                
      <a href="<?php echo $this->baseUrl();?>/products/add" class="btn btn-primary pull-right">Add Products</a>
      <br />
      <br />
          <div class="table-responsive">
            <table class="table table-striped table-bordered">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Name</th>
                  <th>MRP</th>
                  <th>Fact price</th>
                  <th>Price</th>
                  <th>Discount</th>
                  <th>Carat</th>
                  <th>Status</th>
                  <th>Action</th>
                </tr>
              </thead>
              <tbody>
    <?php foreach ( $this->products as $i => $products ): ?>
                <tr>
                  <td><?php echo $i+1; ?></td>
                  <td><?php echo $products['name']; ?></td>
                  <td>Rs <?php echo $products['mrp']; ?> /-</td>
                  <td>Rs <?php echo $products['fact_price']; ?> /-</td>
                  <td>Rs <?php echo $products['price']; ?> /-</td>
                  <td>Rs <?php echo $products['discount']; ?> /-</td>
                  <td><?php echo $products['qty']; ?></td>
                  <td>
                      <?php if( $products['status'] == 'Active') : ?>
                      <span  class="label label-success"><?php echo $products['status']; ?></span>
                      <?php else : ?>
                      <span  class="label label-danger"><?php echo $products['status']; ?></span>
                      <?php endif;?>
                  </td>
                  
                  <td><a href="<?php echo $this->baseUrl(); ?>/products/index/delete/?id=<?php echo $products['id']; ?>" class="btn btn-sm btn-danger">Delete</a>
                  <a href="<?php echo $this->baseUrl(); ?>/products/edit/?id=<?php echo $products['id']; ?>" class="btn btn-sm btn-info">Edit</a>
                  </td>
                </tr>
    <?php endforeach; ?>
              </tbody>
              <tfoot>
                <tr>
                    <td colspan="12" align="middle"><?php echo $this->paginationControl($this->products,
                                    'Sliding',
                                    'my_pagination_control.phtml'); ?></td>
                </tr>
              </tfoot>
            </table>
            
          </div>
        </div>