<h1 class="page-header">Users Password</h1>

<div class="row">
<?php foreach ( $this->messages as $msg ) : ?>
     <?php echo $msg; ?>
<?php endforeach;?>
    
    <form role="form" method="post">
        <div class="form-group">
    <label for="npass">New Password</label>
    <input type="text" class="form-control" id="npass" name="npass" placeholder="New Password">
  </div>
   
  <div class="form-group">
    <label for="opass">Old Password</label>
    <input type="text" class="form-control" id="opass" name="opass" placeholder="Old Password">
  </div>
 
  <button type="submit" class="btn btn-default">Submit</button>
</form>
</div>