<!--
See http://developer.yahoo.com/ypatterns/pattern.php?pattern=searchpagination
-->
 
<?php if ($this->pageCount): ?>
<ul class="pagination pagination-sm">
<!-- Previous page link -->
<?php if (isset($this->previous)): ?>
 <li> 
 <a href="<?php echo $this->url(array('page' => $this->previous)); ?>"> &lt; Previous</a> 
 </li>
<?php else: ?>
  <li class="disabled"><a> &lt; Previous </a></li> 
<?php endif; ?>
 
<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page): ?>
  <?php if ($page != $this->current): ?>
    <li><a href="<?php echo $this->url(array('page' => $page)); ?>">
        <?php echo $page; ?>
    </a> </li> 
  <?php else: ?>
    <li> <a> <?php echo $page; ?> </a></li>
  <?php endif; ?>
<?php endforeach; ?>
 
<!-- Next page link -->
<?php if (isset($this->next)): ?>
  <li>
  <a href="<?php echo $this->url(array('page' => $this->next)); ?>">
    Next &gt;
  </a>
  </li>
<?php else: ?>
  <li class="disabled"><a>Next &gt;</a></li>
<?php endif; ?>
</ul>
<?php endif; ?>