<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>::Dashboard</title>

    <!-- Bootstrap core CSS -->
    <link href="<?php echo $this->baseUrl();?>/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="<?php echo $this->baseUrl();?>/css/dashboard.css" rel="stylesheet">
<link href="<?php echo $this->baseUrl();?>/css/navbar.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy this line! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <!-- Fixed navbar -->
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Gyan</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="<?php echo $this->baseUrl(); ?>/dashboard">Dashboard</a></li>
            <li><a href="<?php echo $this->baseUrl(); ?>/products">Products</a></li>
            <li><a href="<?php echo $this->baseUrl(); ?>/users">Users</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Settings <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="#">Profile</a></li>
                <li><a href="#">Change password</a></li>
                <li class="divider"></li>
                <li class="dropdown-header"></li>
                <li><a href="<?php echo $this->baseUrl();?>/index/logout">Logout</a></li>
              </ul>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
          	<li><a href="#about">Welcome, <?php echo $this->current_user_name; ?></a></li>
            <li><a href="#"><span class="badge">0</span> &nbsp;Notifications</a></li>
            <li class="active"><a href="<?php echo $this->baseUrl();?>/index/logout">Logout <span class="glyphicon glyphicon-off"></span></a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
            <li class="active"><a href="<?php echo $this->baseUrl(); ?>/dashboard">Overview</a></li>
            <li><a href="<?php echo $this->baseUrl(); ?>/users">Users Management</a></li>
            <li><a href="<?php echo $this->baseUrl(); ?>/products">Product Management</a></li>
            
            <li><a href="#">#</a></li>
          </ul>
          <ul class="nav nav-sidebar">
            <li><a href="">#</a></li>
            <li><a href="">#</a></li>
            <li><a href="">#</a></li>
            <li><a href="">#</a></li>
            <li><a href="">#</a></li>
          </ul>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
	    <hr />
     		<?php echo $this->layout()->content; ?>
      </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="<?php echo $this->baseUrl();?>/bootstrap/js/bootstrap.min.js"></script>
  </body>
</html>
