
<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Gyan</title>

    <!-- Core CSS - Include with every page -->
    <link href="<?php echo $this->baseUrl();?>/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="<?php echo $this->baseUrl();?>/css/font-awesome.css" rel="stylesheet">

    <!-- Page-Level Plugin CSS - Dashboard -->
    <link href="<?php echo $this->baseUrl();?>/css/morris-0.4.3.min.css" rel="stylesheet">
    <link href="css/plugins/timeline/timeline.css" rel="stylesheet">

    <!-- SB Admin CSS - Include with every page -->
    <link href="<?php echo $this->baseUrl();?>/css/layout.css" rel="stylesheet">

</head>

<body>

    <div id="wrapper">

        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="index.html">Gyan</a>
            </div>
            <!-- /.navbar-header -->
            
             <ul class="nav navbar-nav">
            <li class="active"><a href="<?php echo $this->baseUrl();?>/dashboard">Dashboard</a></li>
            <li><a href="<?php echo $this->baseUrl();?>/products">Products</a></li>
            <li><a href="<?php echo $this->baseUrl();?>/users">Users</a></li>
            <li><a href="<?php echo $this->baseUrl();?>/demands">Demands</a></li>
            <li><a href="<?php echo $this->baseUrl();?>/distributors">Distributors</a></li>
            </ul>

            <ul class="nav navbar-top-links navbar-right">
                <!-- /.dropdown -->
              
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" >
                        Notifications <i class="glyphicon glyphicon-bell"></i>  <b class="caret"></b>
                    </a>
                    
                    <ul class="dropdown-menu dropdown-alerts">
                        <li>
                            <a href="#">
                                <div>
                                    <i class="fa fa-comment fa-fw"></i> New Comment
                                    <span class="pull-right text-muted small">4 minutes ago</span>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">
                                <div>
                                    <i class="fa fa-twitter fa-fw"></i> 3 New Followers
                                    <span class="pull-right text-muted small">12 minutes ago</span>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">
                                <div>
                                    <i class="fa fa-envelope fa-fw"></i> Message Sent
                                    <span class="pull-right text-muted small">4 minutes ago</span>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">
                                <div>
                                    <i class="fa fa-tasks fa-fw"></i> New Task
                                    <span class="pull-right text-muted small">4 minutes ago</span>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">
                                <div>
                                    <i class="fa fa-upload fa-fw"></i> Server Rebooted
                                    <span class="pull-right text-muted small">4 minutes ago</span>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a class="text-center" href="#">
                                <strong>See All Alerts</strong>
                                <i class="fa fa-angle-right"></i>
                            </a>
                        </li>
                    </ul>
                    <!-- /.dropdown-alerts -->
                </li>
                <!-- /.dropdown -->
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <?php echo $this->current_user_name; ?> <i class="glyphicon glyphicon-user"></i>  <i class="caret "></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user ">
                        <li><a href="#"><i class="glyphicon glyphicon-user"></i> User Profile</a>
                        </li>
                        <li><a href="<?php echo $this->baseUrl();?>/users/index/changepassword"><i class="glyphicon glyphicon-cog"></i> Settings</a>
                        </li>
                        <li class="divider"></li>
                        <li><a href="<?php echo $this->baseUrl();?>/index/logout"><i class="glyphicon glyphicon-log-out"></i> Logout</a>
                        </li>
                    </ul>
                    <!-- /.dropdown-user -->
                </li>
                <!-- /.dropdown -->
            </ul>
            <!-- /.navbar-top-links -->

            <div class="navbar-default navbar-static-side" role="navigation">
                <div class="sidebar-collapse">
                    <ul class="nav" id="side-menu">
                       
                        <li>
                            <a href="<?php echo $this->baseUrl(); ?>/dashboard"><i class="glyphicon glyphicon-align-center"></i> Dashboard</a>
                        </li>
                        <li>
                            <a href="<?php echo $this->baseUrl(); ?>/users"><i class="glyphicon glyphicon-user"></i> Users Management<span class="arrow">&raquo;</span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="<?php echo $this->baseUrl(); ?>/users">Manage</a>
                                </li>
                                <li>
                                    <a href="<?php echo $this->baseUrl(); ?>/users/add">Add user</a>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                        <li>
                            <a href="<?php echo $this->baseUrl(); ?>/products"><i class="glyphicon glyphicon-shopping-cart"></i> Product Management <span class="arrow">&raquo;</span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="<?php echo $this->baseUrl(); ?>/products">Manage</a>
                                </li>
                                <li>
                                    <a href="<?php echo $this->baseUrl(); ?>/products/add">Add product</a>
                                </li>
                            </ul>
                        </li>
                        <li>
                            <a href="<?php echo $this->baseUrl(); ?>/distributors"><i class="glyphicon glyphicon-globe"></i> Distributors Management <span class="arrow">&raquo;</span></a>
                             <ul class="nav nav-second-level">
                                <li>
                                    <a href="<?php echo $this->baseUrl(); ?>/distributors">Manage</a>
                                </li>
                                <li>
                                    <a href="<?php echo $this->baseUrl(); ?>/distributors/add">Add distributors</a>
                                </li>
                            </ul>
                        </li>
                        <li>
                            <a href="<?php echo $this->baseUrl(); ?>/demands"><i class="glyphicon glyphicon-usd"></i> Demands Management<span class="arrow">&raquo;</span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="<?php echo $this->baseUrl(); ?>/demands">Manage</a>
                                </li>
                                <li>
                                    <a href="<?php echo $this->baseUrl(); ?>/demands/add">Add demands</a>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>

                    </ul>
                    <!-- /#side-menu -->
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>

        <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    
                    <?php echo $this->layout()->content; ?>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->

    <!-- Core Scripts - Include with every page -->
    <script src="<?php echo $this->baseUrl();?>/js/jquery-1.10.2.js"></script>
    <script src="<?php echo $this->baseUrl();?>/bootstrap/js/bootstrap.min.js"></script>
    <script src="<?php echo $this->baseUrl();?>/js/jquery.metisMenu.js"></script>

    <!-- Page-Level Plugin Scripts - Dashboard -->
    <script src="js/plugins/morris/raphael-2.1.0.min.js"></script>
    <script src="js/plugins/morris/morris.js"></script>

    <!-- SB Admin Scripts - Include with every page -->
    <script src="<?php echo $this->baseUrl();?>/js/sb-admin.js"></script>

    <!-- Page-Level Demo Scripts - Dashboard - Use for reference -->
    <script src="js/demo/dashboard-demo.js"></script>

</body>

</html>
