<h1 class="page-header text-primary">Edit Demands</h1>

<div class="row">
<?php foreach ( $this->messages as $msg ) : ?>
     <?php echo $msg; ?>
<?php endforeach;?>
    
    <form role="form" method="post">
    
      <div class="form-group">
    <label for="name">Title</label>
    <input type="text" class="form-control" id="title" name="title" placeholder="Title" value="<?php echo $this->demands['title'];?>">
  </div>
  
  <div class="form-group">
    <label for="product_id">Product</label>
    <select name="product_id" class="form-control">
        <option value="">select</option>
        <?php foreach ( $this->products as $products ) : ?>
        <option value="<?php echo $products['id']; ?>" <?php echo $this->demands['product_id'] == $products['id']? 'Selected':''; ?>><?php echo $products['name']; ?></option>
        <?php endforeach;?>
    </select>
  </div>
  
  <div class="form-group">
    <label for="caret">Caret</label>
    <input type="text" class="form-control" id="caret" name="caret" placeholder="Caret" value="<?php echo $this->demands['caret'];?>">
  </div>
    
    <div class="form-group">
    <label for="role">Distributors</label>
    <select name="distributors_id" class="form-control">
        <option value="">select</option>
        <?php foreach ( $this->distributors as $distributors ) : ?>
        <option value="<?php echo $distributors['id']; ?>" <?php echo $this->demands['distributors_id'] == $distributors['id']? 'Selected':''; ?>><?php echo $distributors['initial_name'], ' ', $distributors['name']; ?></option>
        <?php endforeach;?>
    </select>
  </div>
    
   <div class="form-group ">
    <label for="address">Details</label>
    
    <!--<input type="email" class="form-control" id="email" name="email" placeholder="Enter email">-->
    <textarea name="details" id="details" class="form-control" rows="5"><?php echo $this->demands['details'];?></textarea>
    
  </div>
  
  <div class="checkbox">
    <label>
        <input type="checkbox" name="forward" value="Yes" <?php echo $this->demands['forward'] == 'Yes'? 'Checked':''; ?> > Forward to plant
    </label>
  </div>
  <input type="hidden" name="id" value="<?php echo $this->demands['id'];?>" />
  <button type="submit" class="btn btn-default">Submit</button>
</form>
</div>