<h1 class="page-header text-info">Demands</h1>
<div class="breadcrumb"><a href="<?php echo $this->baseUrl();?>/dashboard" class="small">Dashboard</a> / <span class="small text-muted">Demands</span></div>
  <div class="row">
      <?php foreach ($this->messages as $message) : ?>
		<li class="label label-danger"><?php echo $this->escape($message); ?></li>
<?php endforeach; ?>
          
          <?php if( $this->u_type != 4 ) : ?>      
     <a href="<?php echo $this->baseUrl();?>/demands/add" class="btn btn-primary pull-right">Add Demands</a> <br /><br />
     <?php endif; ?>
     
     
          <div class="table-responsive">
            <table class="table table-striped table-bordered">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Title</th>
                  <th>Product name</th>
                  <th>Caret</th>
                  <th>Distributor</th>
                  <th>Added by</th>
                  <th>Plant</th>
                  <th>Approved</th>
                  <th>Supplied</th>
                  <th>Print</th>
                  <th>Action</th>
                </tr>
              </thead>
              <tbody>
    <?php foreach ( $this->demands as $i => $demands ): ?>
                <tr>
                  <td><?php echo $i+1; ?></td>
                  <td class="small"><?php echo substr($demands['title'], 0, 6); ?>..</td>
                  <td class="small"><?php echo $demands['pname']; ?></td>
                  <td><?php echo $demands['caret']; ?></td>
                  <td class="small"><?php echo $demands['initial_name']; ?> <?php echo $demands['name']; ?></td>
                  <td class="small"><?php echo $demands['uname']; ?> | <small class="text-warning"> ( <?php echo str_replace( '_', ' ', $demands['u_type'] ); ?> ) </small></td>
                  <td>
                      <?php if( $demands['forward'] == 'Yes') : ?>
                      <span  class="label label-success"><?php echo $demands['forward']; ?></span>
                      <?php else : ?>
                      <span  class="label label-danger"><?php echo $demands['forward']; ?></span>
                      <?php endif;?>
                  </td>
                  <td>
                     <?php if($this->u_type == 3): echo $demands['approved']? 'Yes' : 'No'; ?>
                     
                     <?php elseif( $demands['approved'] == '1') : ?>
                      &nbsp;<a><span class="glyphicon glyphicon-ok-sign"></span> </a>
                      <?php else : ?>
                       &nbsp;<a href="<?php echo $this->baseUrl(); ?>/demands/index/approve/?id=<?php echo $demands['did']; ?>" > <span class="glyphicon glyphicon-remove-sign" title="Click to approve"></span> </a>
                      <?php endif;?>
                  </td>
                  <td><?php echo $demands['supplied']; ?></td>
                  <td><a> <span class="glyphicon glyphicon-print"></span> </a></td>
                  <td>
                  <?php if($this->u_type != 3) : ?>
                  <i class="glyphicon glyphicon-envelope" title="Send SMS" data-toggle="modal" data-target=".bs-example-modal-sm"></i>
                  <?php endif; ?>
                  
                  &nbsp;
                  <a href="<?php echo $this->baseUrl(); ?>/demands/index/delete/?id=<?php echo $demands['did']; ?>" class="btn btn-sm btn-danger">Delete</a>
                  <?php if( $demands['supplied'] == 'No') : ?>
                  <a href="<?php echo $this->baseUrl(); ?>/demands/edit/?id=<?php echo $demands['did']; ?>" class="btn btn-sm btn-info">Edit</a>
                  <?php endif; ?>
                  
                  </td>
                </tr>
    <?php endforeach; ?>
              </tbody>
              <tfoot>
                <tr>
                    <td colspan="12" align="middle"><?php echo $this->paginationControl($this->demands,
                                    'Sliding',
                                    'my_pagination_control.phtml'); ?></td>
                </tr>
              </tfoot>
            </table>
            
          </div>
        </div>
        

<!-- SMS POPUP -->

<div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Sms</h4>
      </div>
      <div class="modal-body">
         <form>
          
     <div class="form-group ">
    <label for="message">Message</label>
    
    <!--<input type="email" class="form-control" id="email" name="email" placeholder="Enter email">-->
    <textarea name="message" id="message" class="form-control" rows="3" placeholder="Type message..."></textarea>
    
  </div>
         
         </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary ">Send</button>
      </div>
    </div>
  </div>
</div>



